### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Apocryphon-X** [Mau-MD/omegaUp-CPC#1]
Al ejecutar por primera vez `main.py` sale el siguiente error:

```py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from util import get_credentials_from_file, print_table, path_exists
  File "/home/apocryphon/packages/omegaUp-CPC/util.py", line 28, in <module>
    def print_table(rows: list[str]):
TypeError: 'type' object is not subscriptable
```

Temporalmente, logre ejecutarlo usando `ipython` en su lugar

**Comment by Apocryphon-X** [comment]
Creo que es un problema con la version de Python, use la 3.8 pero `ipython` usa la 3.10

**Comment by Mau-MD** [comment]
Si, es por la versión. Corrí con Python 3.8 y me marcó el mismo error. El error fue causado específicamente por fijar un tipo dentro del parámetro `rows: list[str]` dentro de la función
